version: "3"
services:
  api:
    container_name: api
    build: . # Localisation du Dockerfile dans notre cas dans le dossier racine
    ports:
      - 5000:5000 # Nous exposons le port 5000
    environment:
      - PORT=5000 # Nous pouvons définir ici plusieurs variables d'environnement
    depends_on:
      - database
    networks:
      - test-net
  database:
    image: 'mongo'
    container_name: database
    environment: 
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: amaury1504
      MONGO_INITDB_ROOT_PASSWORD: amaury1504
    ports:
      - '27017-27019:27017-27019'
# Définition des volumes:
volumes:
  mongo-storage:
    driver: local
networks:
  test-net:
